In [ ]:
# merging
import pandas as pd
df_tab1 = pd.DataFrame({
    'id': [1,2,3,4],
    'name': ['ram', 'shyam', 'hari','']
})

df_tab2 = pd.DataFrame({
    'id': [1,2,3,4,5],
    'marks':[20,30, 55, 43, 22]
})

df_tab3= pd.merge(df_tab1, df_tab2 , on='id', how='outer')
df_tab3

   id   name  marks
0   1    ram     20
1   2  shyam     30
2   3   hari     55
3   4            43
4   5    NaN     22

In [ ]:
# joining--> combined df using index instead of columns
df_tab1 = pd.DataFrame({
    # 'id': [1,2,3,4],
    'name': ['ram', 'shyam', 'hari','unknown']
}, index=[1,2,3,4])

df_tab2 = pd.DataFrame({
    # 'id': [1,2,3,4,5],
    'marks':[20,30, 55, 43, 22]
}, index=[1,2,3,4,5])

df_tab3= df_tab1.join(df_tab2, how='inner')
df_tab3
# its use case is little different, use it for joining different
#  measurements like temp in table 1 and humidity in table 2

      name  marks
1      ram     20
2    shyam     30
3     hari     55
4  unknown     43

In [ ]:
# melt -- wide --> long
df_scores = pd.DataFrame({
    'Student':['Ram', 'Hari'],
    'math': [30, 19],
    'english': [12, 32]
})
print(df_scores) # this format is wide format

# lets change it into long format
melted = pd.melt(
    df_scores,
    id_vars=['Student'],
    var_name='Subject',
    value_name='Score'
)
melted

  Student  math  english
0     Ram    30       12
1    Hari    19       32

  Student  Subject  Score
0     Ram     math     30
1    Hari     math     19
2     Ram  english     12
3    Hari  english     32

In [23]:
# pivot -- long-->wide
df_long = pd.DataFrame({
    'Student':['Ram', 'Ram','Hari', 'Hari'],
    'Subject': ['math', 'english','math', 'english'],
    'Score': [10, 43, 54, 23]
})
print(df_long)

pivoted = df_long.pivot(
    index='Student',
    columns='Subject',
    values='Score'
)
pivoted

  Student  Subject  Score
0     Ram     math     10
1     Ram  english     43
2    Hari     math     54
3    Hari  english     23

Subject  english  math
Student
Hari          23    54
Ram           43    10

In [24]:
# another method is stack
stacked = df_long.stack()
print(stacked)

0  Student        Ram
   Subject       math
   Score           10
1  Student        Ram
   Subject    english
   Score           43
2  Student       Hari
   Subject       math
   Score           54
3  Student       Hari
   Subject    english
   Score           23
dtype: object

In [32]:
# log transformation
import numpy as np
import pandas as pd

x=pd.Series([1,10,100,1000])
x_log = np.log1p(x)
print(x_log)

0    0.693147
1    2.397895
2    4.615121
3    6.908755
dtype: float64

In [33]:
x_sqrt = np.sqrt(x)
x_sqrt

0     1.000000
1     3.162278
2    10.000000
3    31.622777
dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
x = np.array([[200],[300],[400],[600],[1000]])
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(x)
print(scaled_data)
# range(0,1)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.5  ]
 [1.   ]]

In [37]:
# z-score normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(x)
scaled_data

array([[-1.06066017],
       [-0.70710678],
       [-0.35355339],
       [ 0.35355339],
       [ 1.76776695]])

In [ ]:
# label encoding -->best to use for ordinal data(not nomial)
from sklearn.preprocessing import LabelEncoder
cities=['kathmandu','pokhara','butwal']
le=LabelEncoder()
encoded = le.fit_transform(cities)
encoded

array([1, 2, 0])

In [43]:
# one hot encoding
df = pd.DataFrame({'city':['kathmandu','pokhara','butwal']})
encoded = pd.get_dummies(df, columns=['city'])
encoded

   city_butwal  city_kathmandu  city_pokhara
0        False            True         False
1        False           False          True
2         True           False         False

In [44]:
from sklearn.preprocessing import OrdinalEncoder
quality = [['poor'],['medium'],['high']]
encoder = OrdinalEncoder()
encoded = encoder.fit_transform(quality)
encoded

array([[2.],
       [1.],
       [0.]])

In [46]:
# # memory optimization 
# 1. use smaller datatypes
# 2. change object to category
# 3. chunking
# 4. Inplace operations
# 5. garbage collection

# # efficient data processing
# 1. vectorized processing instead of loops
# 2. parellel processing - from multiprocessing import pool 
# 3. lazy evaluation

In [47]:
# # data cleaning pipeline
# 1. data loading 
# 2. handling missing values
# 3. duplicates removal
# 4. datatype correction
# 5. outlier detection and removal
# 6. feature transformation 
# 7. export cleaned data