In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'ID':[1,2,3],
    'Name':['Ram','Shyam','Hari'],
    'Level':['low','medium','high']
})

In [3]:
df["Level"]=df['Level'].astype('category')

In [4]:
df['Level'].cat.codes
print(df)

   ID   Name   Level
0   1    Ram     low
1   2  Shyam  medium
2   3   Hari    high

In [5]:
encoded = pd.get_dummies(df['Level'],prefix='Lev',dtype=int)
print(encoded)

   Lev_high  Lev_low  Lev_medium
0         0        1           0
1         0        0           1
2         1        0           0

In [6]:
df_final= pd.concat([df,encoded],axis=1)
print(df_final)

   ID   Name   Level  Lev_high  Lev_low  Lev_medium
0   1    Ram     low         0        1           0
1   2  Shyam  medium         0        0           1
2   3   Hari    high         1        0           0

time series

In [7]:
df = pd.DataFrame({
    'Date':['2026-01-01','2026-01-02','2026-01-03','2026-01-04'],
    'Sales': [200,302,201,150]
})
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4 non-null      object
 1   Sales   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

         Date  Sales
0  2026-01-01    200
1  2026-01-02    302
2  2026-01-03    201
3  2026-01-04    150

In [8]:
df['Date']=pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4 non-null      datetime64[ns]
 1   Sales   4 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 196.0 bytes

In [9]:
df=df.set_index('Date')
df

            Sales
Date
2026-01-01    200
2026-01-02    302
2026-01-03    201
2026-01-04    150

In [15]:
df['Year']=df.index.year
df['Month']=df.index.month
df['Day']=df.index.day_name()
df

            Sales  Year  Month       Day
Date
2026-01-01    200  2026      1  Thursday
2026-01-02    302  2026      1    Friday
2026-01-03    201  2026      1  Saturday
2026-01-04    150  2026      1    Sunday

In [17]:
df.loc['2026-01-01':'2026-01-02']

            Sales  Year  Month       Day
Date
2026-01-01    200  2026      1  Thursday
2026-01-02    302  2026      1    Friday

In [18]:
df.loc['2026-01']

            Sales  Year  Month       Day
Date
2026-01-01    200  2026      1  Thursday
2026-01-02    302  2026      1    Friday
2026-01-03    201  2026      1  Saturday
2026-01-04    150  2026      1    Sunday

In [22]:
df.to_csv('dates.csv')

In [23]:
new_df= pd.read_csv(
    "dates.csv",
    parse_dates=['Date'],
    index_col='Date'
)
new_df

            Sales  Year  Month       Day
Date
2026-01-01    200  2026      1  Thursday
2026-01-02    302  2026      1    Friday
2026-01-03    201  2026      1  Saturday
2026-01-04    150  2026      1    Sunday